projects:
  superformulatesttask:
    schemaPath: src/graphql/schema.json
    includes:
      - src/lib/apis/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/lib/apis/graphql/API.ts
        docsFilePath: src/lib/apis/graphql
